/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.spark.tracing;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2017-1-19")
public class TaskSetInfo implements org.apache.thrift.TBase<TaskSetInfo, TaskSetInfo._Fields>, java.io.Serializable, Cloneable, Comparable<TaskSetInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TaskSetInfo");

  private static final org.apache.thrift.protocol.TField TASK_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("taskSet", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField SUBMIT_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("submitTime", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField STAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("stageId", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField STAGE_ATTEMPT_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("stageAttemptId", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField JOB_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("jobId", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField APP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("appId", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TaskSetInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TaskSetInfoTupleSchemeFactory());
  }

  public Set<TaskInfo> taskSet; // required
  public long submitTime; // required
  public int stageId; // required
  public int stageAttemptId; // required
  public int jobId; // required
  public String appId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TASK_SET((short)1, "taskSet"),
    SUBMIT_TIME((short)2, "submitTime"),
    STAGE_ID((short)3, "stageId"),
    STAGE_ATTEMPT_ID((short)4, "stageAttemptId"),
    JOB_ID((short)5, "jobId"),
    APP_ID((short)6, "appId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASK_SET
          return TASK_SET;
        case 2: // SUBMIT_TIME
          return SUBMIT_TIME;
        case 3: // STAGE_ID
          return STAGE_ID;
        case 4: // STAGE_ATTEMPT_ID
          return STAGE_ATTEMPT_ID;
        case 5: // JOB_ID
          return JOB_ID;
        case 6: // APP_ID
          return APP_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SUBMITTIME_ISSET_ID = 0;
  private static final int __STAGEID_ISSET_ID = 1;
  private static final int __STAGEATTEMPTID_ISSET_ID = 2;
  private static final int __JOBID_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASK_SET, new org.apache.thrift.meta_data.FieldMetaData("taskSet", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "TaskInfo"))));
    tmpMap.put(_Fields.SUBMIT_TIME, new org.apache.thrift.meta_data.FieldMetaData("submitTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("stageId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.STAGE_ATTEMPT_ID, new org.apache.thrift.meta_data.FieldMetaData("stageAttemptId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.JOB_ID, new org.apache.thrift.meta_data.FieldMetaData("jobId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.APP_ID, new org.apache.thrift.meta_data.FieldMetaData("appId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TaskSetInfo.class, metaDataMap);
  }

  public TaskSetInfo() {
  }

  public TaskSetInfo(
    Set<TaskInfo> taskSet,
    long submitTime,
    int stageId,
    int stageAttemptId,
    int jobId,
    String appId)
  {
    this();
    this.taskSet = taskSet;
    this.submitTime = submitTime;
    setSubmitTimeIsSet(true);
    this.stageId = stageId;
    setStageIdIsSet(true);
    this.stageAttemptId = stageAttemptId;
    setStageAttemptIdIsSet(true);
    this.jobId = jobId;
    setJobIdIsSet(true);
    this.appId = appId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TaskSetInfo(TaskSetInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetTaskSet()) {
      Set<TaskInfo> __this__taskSet = new HashSet<TaskInfo>(other.taskSet.size());
      for (TaskInfo other_element : other.taskSet) {
        __this__taskSet.add(other_element);
      }
      this.taskSet = __this__taskSet;
    }
    this.submitTime = other.submitTime;
    this.stageId = other.stageId;
    this.stageAttemptId = other.stageAttemptId;
    this.jobId = other.jobId;
    if (other.isSetAppId()) {
      this.appId = other.appId;
    }
  }

  public TaskSetInfo deepCopy() {
    return new TaskSetInfo(this);
  }

  @Override
  public void clear() {
    this.taskSet = null;
    setSubmitTimeIsSet(false);
    this.submitTime = 0;
    setStageIdIsSet(false);
    this.stageId = 0;
    setStageAttemptIdIsSet(false);
    this.stageAttemptId = 0;
    setJobIdIsSet(false);
    this.jobId = 0;
    this.appId = null;
  }

  public int getTaskSetSize() {
    return (this.taskSet == null) ? 0 : this.taskSet.size();
  }

  public java.util.Iterator<TaskInfo> getTaskSetIterator() {
    return (this.taskSet == null) ? null : this.taskSet.iterator();
  }

  public void addToTaskSet(TaskInfo elem) {
    if (this.taskSet == null) {
      this.taskSet = new HashSet<TaskInfo>();
    }
    this.taskSet.add(elem);
  }

  public Set<TaskInfo> getTaskSet() {
    return this.taskSet;
  }

  public TaskSetInfo setTaskSet(Set<TaskInfo> taskSet) {
    this.taskSet = taskSet;
    return this;
  }

  public void unsetTaskSet() {
    this.taskSet = null;
  }

  /** Returns true if field taskSet is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskSet() {
    return this.taskSet != null;
  }

  public void setTaskSetIsSet(boolean value) {
    if (!value) {
      this.taskSet = null;
    }
  }

  public long getSubmitTime() {
    return this.submitTime;
  }

  public TaskSetInfo setSubmitTime(long submitTime) {
    this.submitTime = submitTime;
    setSubmitTimeIsSet(true);
    return this;
  }

  public void unsetSubmitTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUBMITTIME_ISSET_ID);
  }

  /** Returns true if field submitTime is set (has been assigned a value) and false otherwise */
  public boolean isSetSubmitTime() {
    return EncodingUtils.testBit(__isset_bitfield, __SUBMITTIME_ISSET_ID);
  }

  public void setSubmitTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUBMITTIME_ISSET_ID, value);
  }

  public int getStageId() {
    return this.stageId;
  }

  public TaskSetInfo setStageId(int stageId) {
    this.stageId = stageId;
    setStageIdIsSet(true);
    return this;
  }

  public void unsetStageId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STAGEID_ISSET_ID);
  }

  /** Returns true if field stageId is set (has been assigned a value) and false otherwise */
  public boolean isSetStageId() {
    return EncodingUtils.testBit(__isset_bitfield, __STAGEID_ISSET_ID);
  }

  public void setStageIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STAGEID_ISSET_ID, value);
  }

  public int getStageAttemptId() {
    return this.stageAttemptId;
  }

  public TaskSetInfo setStageAttemptId(int stageAttemptId) {
    this.stageAttemptId = stageAttemptId;
    setStageAttemptIdIsSet(true);
    return this;
  }

  public void unsetStageAttemptId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __STAGEATTEMPTID_ISSET_ID);
  }

  /** Returns true if field stageAttemptId is set (has been assigned a value) and false otherwise */
  public boolean isSetStageAttemptId() {
    return EncodingUtils.testBit(__isset_bitfield, __STAGEATTEMPTID_ISSET_ID);
  }

  public void setStageAttemptIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __STAGEATTEMPTID_ISSET_ID, value);
  }

  public int getJobId() {
    return this.jobId;
  }

  public TaskSetInfo setJobId(int jobId) {
    this.jobId = jobId;
    setJobIdIsSet(true);
    return this;
  }

  public void unsetJobId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __JOBID_ISSET_ID);
  }

  /** Returns true if field jobId is set (has been assigned a value) and false otherwise */
  public boolean isSetJobId() {
    return EncodingUtils.testBit(__isset_bitfield, __JOBID_ISSET_ID);
  }

  public void setJobIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __JOBID_ISSET_ID, value);
  }

  public String getAppId() {
    return this.appId;
  }

  public TaskSetInfo setAppId(String appId) {
    this.appId = appId;
    return this;
  }

  public void unsetAppId() {
    this.appId = null;
  }

  /** Returns true if field appId is set (has been assigned a value) and false otherwise */
  public boolean isSetAppId() {
    return this.appId != null;
  }

  public void setAppIdIsSet(boolean value) {
    if (!value) {
      this.appId = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TASK_SET:
      if (value == null) {
        unsetTaskSet();
      } else {
        setTaskSet((Set<TaskInfo>)value);
      }
      break;

    case SUBMIT_TIME:
      if (value == null) {
        unsetSubmitTime();
      } else {
        setSubmitTime((Long)value);
      }
      break;

    case STAGE_ID:
      if (value == null) {
        unsetStageId();
      } else {
        setStageId((Integer)value);
      }
      break;

    case STAGE_ATTEMPT_ID:
      if (value == null) {
        unsetStageAttemptId();
      } else {
        setStageAttemptId((Integer)value);
      }
      break;

    case JOB_ID:
      if (value == null) {
        unsetJobId();
      } else {
        setJobId((Integer)value);
      }
      break;

    case APP_ID:
      if (value == null) {
        unsetAppId();
      } else {
        setAppId((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TASK_SET:
      return getTaskSet();

    case SUBMIT_TIME:
      return Long.valueOf(getSubmitTime());

    case STAGE_ID:
      return Integer.valueOf(getStageId());

    case STAGE_ATTEMPT_ID:
      return Integer.valueOf(getStageAttemptId());

    case JOB_ID:
      return Integer.valueOf(getJobId());

    case APP_ID:
      return getAppId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TASK_SET:
      return isSetTaskSet();
    case SUBMIT_TIME:
      return isSetSubmitTime();
    case STAGE_ID:
      return isSetStageId();
    case STAGE_ATTEMPT_ID:
      return isSetStageAttemptId();
    case JOB_ID:
      return isSetJobId();
    case APP_ID:
      return isSetAppId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TaskSetInfo)
      return this.equals((TaskSetInfo)that);
    return false;
  }

  public boolean equals(TaskSetInfo that) {
    if (that == null)
      return false;

    boolean this_present_taskSet = true && this.isSetTaskSet();
    boolean that_present_taskSet = true && that.isSetTaskSet();
    if (this_present_taskSet || that_present_taskSet) {
      if (!(this_present_taskSet && that_present_taskSet))
        return false;
      if (!this.taskSet.equals(that.taskSet))
        return false;
    }

    boolean this_present_submitTime = true;
    boolean that_present_submitTime = true;
    if (this_present_submitTime || that_present_submitTime) {
      if (!(this_present_submitTime && that_present_submitTime))
        return false;
      if (this.submitTime != that.submitTime)
        return false;
    }

    boolean this_present_stageId = true;
    boolean that_present_stageId = true;
    if (this_present_stageId || that_present_stageId) {
      if (!(this_present_stageId && that_present_stageId))
        return false;
      if (this.stageId != that.stageId)
        return false;
    }

    boolean this_present_stageAttemptId = true;
    boolean that_present_stageAttemptId = true;
    if (this_present_stageAttemptId || that_present_stageAttemptId) {
      if (!(this_present_stageAttemptId && that_present_stageAttemptId))
        return false;
      if (this.stageAttemptId != that.stageAttemptId)
        return false;
    }

    boolean this_present_jobId = true;
    boolean that_present_jobId = true;
    if (this_present_jobId || that_present_jobId) {
      if (!(this_present_jobId && that_present_jobId))
        return false;
      if (this.jobId != that.jobId)
        return false;
    }

    boolean this_present_appId = true && this.isSetAppId();
    boolean that_present_appId = true && that.isSetAppId();
    if (this_present_appId || that_present_appId) {
      if (!(this_present_appId && that_present_appId))
        return false;
      if (!this.appId.equals(that.appId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_taskSet = true && (isSetTaskSet());
    list.add(present_taskSet);
    if (present_taskSet)
      list.add(taskSet);

    boolean present_submitTime = true;
    list.add(present_submitTime);
    if (present_submitTime)
      list.add(submitTime);

    boolean present_stageId = true;
    list.add(present_stageId);
    if (present_stageId)
      list.add(stageId);

    boolean present_stageAttemptId = true;
    list.add(present_stageAttemptId);
    if (present_stageAttemptId)
      list.add(stageAttemptId);

    boolean present_jobId = true;
    list.add(present_jobId);
    if (present_jobId)
      list.add(jobId);

    boolean present_appId = true && (isSetAppId());
    list.add(present_appId);
    if (present_appId)
      list.add(appId);

    return list.hashCode();
  }

  @Override
  public int compareTo(TaskSetInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTaskSet()).compareTo(other.isSetTaskSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskSet, other.taskSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSubmitTime()).compareTo(other.isSetSubmitTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSubmitTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.submitTime, other.submitTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStageId()).compareTo(other.isSetStageId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStageId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stageId, other.stageId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetStageAttemptId()).compareTo(other.isSetStageAttemptId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStageAttemptId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stageAttemptId, other.stageAttemptId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetJobId()).compareTo(other.isSetJobId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJobId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jobId, other.jobId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAppId()).compareTo(other.isSetAppId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAppId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.appId, other.appId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TaskSetInfo(");
    boolean first = true;

    sb.append("taskSet:");
    if (this.taskSet == null) {
      sb.append("null");
    } else {
      sb.append(this.taskSet);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("submitTime:");
    sb.append(this.submitTime);
    first = false;
    if (!first) sb.append(", ");
    sb.append("stageId:");
    sb.append(this.stageId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("stageAttemptId:");
    sb.append(this.stageAttemptId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("jobId:");
    sb.append(this.jobId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("appId:");
    if (this.appId == null) {
      sb.append("null");
    } else {
      sb.append(this.appId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TaskSetInfoStandardSchemeFactory implements SchemeFactory {
    public TaskSetInfoStandardScheme getScheme() {
      return new TaskSetInfoStandardScheme();
    }
  }

  private static class TaskSetInfoStandardScheme extends StandardScheme<TaskSetInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TaskSetInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TASK_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.taskSet = new HashSet<TaskInfo>(2*_set0.size);
                TaskInfo _elem1;
                for (int _i2 = 0; _i2 < _set0.size; ++_i2)
                {
                  _elem1 = new TaskInfo();
                  _elem1.read(iprot);
                  struct.taskSet.add(_elem1);
                }
                iprot.readSetEnd();
              }
              struct.setTaskSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SUBMIT_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.submitTime = iprot.readI64();
              struct.setSubmitTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // STAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.stageId = iprot.readI32();
              struct.setStageIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STAGE_ATTEMPT_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.stageAttemptId = iprot.readI32();
              struct.setStageAttemptIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // JOB_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.jobId = iprot.readI32();
              struct.setJobIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // APP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.appId = iprot.readString();
              struct.setAppIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TaskSetInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.taskSet != null) {
        oprot.writeFieldBegin(TASK_SET_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.taskSet.size()));
          for (TaskInfo _iter3 : struct.taskSet)
          {
            _iter3.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SUBMIT_TIME_FIELD_DESC);
      oprot.writeI64(struct.submitTime);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STAGE_ID_FIELD_DESC);
      oprot.writeI32(struct.stageId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(STAGE_ATTEMPT_ID_FIELD_DESC);
      oprot.writeI32(struct.stageAttemptId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(JOB_ID_FIELD_DESC);
      oprot.writeI32(struct.jobId);
      oprot.writeFieldEnd();
      if (struct.appId != null) {
        oprot.writeFieldBegin(APP_ID_FIELD_DESC);
        oprot.writeString(struct.appId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TaskSetInfoTupleSchemeFactory implements SchemeFactory {
    public TaskSetInfoTupleScheme getScheme() {
      return new TaskSetInfoTupleScheme();
    }
  }

  private static class TaskSetInfoTupleScheme extends TupleScheme<TaskSetInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TaskSetInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTaskSet()) {
        optionals.set(0);
      }
      if (struct.isSetSubmitTime()) {
        optionals.set(1);
      }
      if (struct.isSetStageId()) {
        optionals.set(2);
      }
      if (struct.isSetStageAttemptId()) {
        optionals.set(3);
      }
      if (struct.isSetJobId()) {
        optionals.set(4);
      }
      if (struct.isSetAppId()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetTaskSet()) {
        {
          oprot.writeI32(struct.taskSet.size());
          for (TaskInfo _iter4 : struct.taskSet)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetSubmitTime()) {
        oprot.writeI64(struct.submitTime);
      }
      if (struct.isSetStageId()) {
        oprot.writeI32(struct.stageId);
      }
      if (struct.isSetStageAttemptId()) {
        oprot.writeI32(struct.stageAttemptId);
      }
      if (struct.isSetJobId()) {
        oprot.writeI32(struct.jobId);
      }
      if (struct.isSetAppId()) {
        oprot.writeString(struct.appId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TaskSetInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set5 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.taskSet = new HashSet<TaskInfo>(2*_set5.size);
          TaskInfo _elem6;
          for (int _i7 = 0; _i7 < _set5.size; ++_i7)
          {
            _elem6 = new TaskInfo();
            _elem6.read(iprot);
            struct.taskSet.add(_elem6);
          }
        }
        struct.setTaskSetIsSet(true);
      }
      if (incoming.get(1)) {
        struct.submitTime = iprot.readI64();
        struct.setSubmitTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.stageId = iprot.readI32();
        struct.setStageIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.stageAttemptId = iprot.readI32();
        struct.setStageAttemptIdIsSet(true);
      }
      if (incoming.get(4)) {
        struct.jobId = iprot.readI32();
        struct.setJobIdIsSet(true);
      }
      if (incoming.get(5)) {
        struct.appId = iprot.readString();
        struct.setAppIdIsSet(true);
      }
    }
  }

}

